// Regenerates src/fonts/embedded.ts: every TTF in src/fonts/files as base64,
// keyed by FontId, so a consumer can carry the fonts as plain data with no
// file or asset I/O at runtime (the API's Workflow steps on Vercel see neither
// the repository nor Nitro's asset storage). Run it after changing a font:
//
//   npm run fonts:embed        # from packages/core
//
// test/embedded-fonts.test.ts fails whenever the generated file and the TTFs
// disagree, so a stale embed cannot ship unnoticed. The output is
// deterministic: the same files produce the identical module, byte for byte.
//
// Imports the registry directly as TypeScript (Node >= 22.18 strips types
// without a flag), so the FontId -> file mapping has one source of truth.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const { FONT_FILES, FONT_IDS } = await import('../src/fonts/registry.ts')

const filesDir = new URL('../src/fonts/files/', import.meta.url)
const target = new URL('../src/fonts/embedded.ts', import.meta.url)

const entries = FONT_IDS.map((id) => {
  const fileName = FONT_FILES[id]
  const base64 = readFileSync(new URL(fileName, filesDir)).toString('base64')
  return `  // ${fileName}\n  ${JSON.stringify(id)}: ${JSON.stringify(base64)},`
})

const source = `// GENERATED by scripts/embed-fonts.mjs -- do not edit by hand.
// Regenerate with \`npm run fonts:embed\` after changing anything in ./files.
//
// This module is deliberately NOT re-exported from the package index: it is
// ~2.3 MB of base64, meant only for a server bundle that has no other way to
// reach the TTFs. The web app keeps fetching them from /fonts instead.
// Type-only import: Node's type stripping erases it, so this module resolves
// nothing at runtime -- the Workflow step runtime loads this file directly,
// with no bundler to map a relative specifier onto a .ts file. The ids are
// inlined below for the same reason, and the test keeps them honest.
import type { FontBytes, FontId } from './registry'

/** The registry's ids, inlined at generation time (see the note above). */
export const EMBEDDED_FONT_IDS: readonly FontId[] = ${JSON.stringify(FONT_IDS)}

/** Base64 of each TTF in ./files, keyed the same way as FONT_FILES. */
export const EMBEDDED_FONTS: Record<FontId, string> = {
${entries.join('\n')}
}

/**
 * The embedded fonts as bytes, byte-identical to the TTFs in ./files (guarded
 * by test/embedded-fonts.test.ts). Pure: every call decodes anew and hands
 * back fresh buffers, so callers that want one shared instance memoise it.
 * Uses \`atob\` rather than Buffer so it runs anywhere the core does.
 */
export function decodeEmbeddedFonts(): FontBytes {
  const out = {} as FontBytes
  for (const id of EMBEDDED_FONT_IDS) out[id] = decodeBase64(EMBEDDED_FONTS[id])
  return out
}

function decodeBase64(base64: string): Uint8Array {
  const binary = atob(base64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}
`

writeFileSync(target, source)
console.log(`wrote ${fileURLToPath(target)} (${FONT_IDS.length} fonts, ${source.length.toLocaleString()} chars)`)
